### ISSUE TITLE
Wrong Path after image upload and save

### ISSUE THREAD

**Issue by dodiya-divyarajsinh** [studioraz/magento2-category-image#6]
We have implemented this module in Magento 2 version 2.3.4 
We are getting wrong image path after image Upload like https://m2.demo.com/pub/media/catalog/category//pub/media/catalog/tmp/category/federal_1.png 
https://prnt.sc/uz6d60

**Comment by ninex** [comment]
In Helper/Category.php this getImageURL needs to change to the following:
```
public function getImageUrl($image)
    {
        $url = false;
        //$image = $this->getImage();
        if ($image) {
            if (is_string($image)) {
                $url = $this->_urlBuilder->getBaseUrl(
                    ['_type' => \Magento\Framework\UrlInterface::URL_TYPE_WEB]
                ) .  $image;
            } else {
                throw new \Magento\Framework\Exception\LocalizedException(
                    __('Something went wrong while getting the image url.')
                );
            }
        }
        return $url;
    }
```

I hope that helps.

**Comment by dodiya-divyarajsinh** [comment]
@ninex thanks for comment.
The issue is still not fixed. Our issue is /tmp/ is included and saved when we upload images.

**Comment by dodiya-divyarajsinh** [comment]
![Federal-Tire-ID-1675-Categories-Inventory-Catalog-Magento-Admin](https://user-images.githubusercontent.com/25686742/98507563-d7b5ad00-2283-11eb-8612-fdfc55ce2ecd.png)

Image information is not shown after save.
